name: release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    # environment: pastebin.com

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - run: npm ci
      - name: Build
        run: npm run build

      # - name: upload to pastebin.com
      #   env:
      #     PASTEBIN_DEV_KEY: ${{ secrets.PASTEBIN_DEV_KEY }}
      #     PASTEBIN_API_USER_KEY: ${{ secrets.PASTEBIN_API_USER_KEY }}
      #   run: |
      #     chmod +x ./scripts/upload_pastebin.sh
      #     ./scripts/upload_pastebin.sh dist/dist.lua $PASTEBIN_DEV_KEY $PASTEBIN_API_USER_KEY

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: IECOS.lua
      #     path: dist/dist.lua

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: dist/dist.lua
